groups:
- name: Backup
  jobs:
  - backup-opsman
  - backup-elastic-runtime
  - backup-mysql
  - backup-redis
  - backup-rabbitmq
# - name: CleanUp
#   jobs:
#   - clean-up-old-backup-files

resources:
- name: pcf-backup-scripts
  type: git
  source:
    branch: master
    uri: {{git-project-url}}
- name: s3-backup-opsman
  type: s3
  source:
    bucket: {{s3-bucket}}
    regexp: {{s3-bucket-regex}}
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}
# - name: s3-backup-elastic-runtime
#   type: s3
#   source:
#     bucket: {{s3-bucket}}
#     regexp: {{s3-bucket-elastic-runtime-regex}}
#     access_key_id: {{s3-access-key}}
#     secret_access_key: {{s3-secret-access-key}}
# - name: s3-backup-mysql
#   type: s3
#   source:
#     bucket: {{s3-bucket}}
#     regexp: {{s3-bucket-mysql-regex}}
#     access_key_id: {{s3-access-key}}
#     secret_access_key: {{s3-secret-access-key}}
# - name: s3-backup-redis
#   type: s3
#   source:
#     bucket: {{s3-bucket}}
#     regexp: {{s3-bucket-redis-regex}}
#     access_key_id: {{s3-access-key}}
#     secret_access_key: {{s3-secret-access-key}}
# - name: s3-backup-rabbitmq
#   type: s3
#   source:
#     bucket: {{s3-bucket}}
#     regexp: {{s3-bucket-rabbitmq-regex}}
#     access_key_id: {{s3-access-key}}
#     secret_access_key: {{s3-secret-access-key}}
- name: trigger-daily-after-1am
  type: time
  source:
    start: 1:00 AM -0500
    stop: 3:00 AM -0500
- name: trigger-daily-after-5am
  type: time
  source:
    start: 5:00 AM -0500
    stop: 6:00 AM -0500

jobs:
- name: backup-opsman
  serial: true
  public: true
  plan:
  - get: pcf-backup-scripts
    trigger: false
  - get: trigger-daily-after-1am
    trigger: true
  - task: backup-opsman
    file: pcf-backup-scripts/pcf-cfops-backup/ci/tasks/cfops_backup.yml
    params:
      TARGET_TILE: ops-manager
      OPS_MANAGER_HOSTNAME: {{ops-manager-hostname}}
      # OPS_MANAGER_PRIVATE_IP_ADDRESS: {{ops-manager-private-ip}}
      OPS_MANAGER_UI_USER: {{ops-manager-ui-user}}
      OPS_MANAGER_UI_PASSWORD: {{ops-manager-ui-password}}
      OPS_MANAGER_SSH_USER: {{ops-manager-ssh-user}}
      OPS_MANAGER_SSH_PASSWORD: {{ops-manager-ssh-password}}
  - put: s3-backup-opsman-deployments
    params:
      file: ops-manager/opsmanager/(.*).tar.gz
  - put: s3-backup-opsman-installation-1
    params:
      file: ops-manager/opsmanager/(.*).json
  - put: s3-backup-opsman-installation-2
    params:
      file: ops-manager/opsmanager/(.*).zip

# - name: backup-elastic-runtime
#   serial: true
#   public: true
#   plan:
#   - get: pcf-backup-scripts
#     trigger: false
#   - get: trigger-daily-after-1am
#     trigger: true
#     passed:
#       - backup-opsman
#   - task: backup-elastic-runtime
#     file: pcf-backup-scripts/pcf-cfops-backup/ci/tasks/cfops_backup.yml
#     params:
#       TARGET_TILE: elastic-runtime
#       OPS_MANAGER_HOSTNAME: {{ops-manager-hostname}}
#       # OPS_MANAGER_PRIVATE_IP_ADDRESS: {{ops-manager-private-ip}}
#       OPS_MANAGER_UI_USER: {{ops-manager-ui-user}}
#       OPS_MANAGER_UI_PASSWORD: {{ops-manager-ui-password}}
#       OPS_MANAGER_SSH_USER: {{ops-manager-ssh-user}}
#       OPS_MANAGER_SSH_PASSWORD: {{ops-manager-ssh-password}}
#   - put: s3-backup-elastic-runtime
#
# - name: backup-mysql
#   serial: true
#   public: true
#   plan:
#   - get: pcf-backup-scripts
#     trigger: false
#   - get: trigger-daily-after-1am
#     trigger: true
#     passed:
#       - backup-elastic-runtime
#   - task: backup-mysql
#     file: pcf-backup-scripts/pcf-cfops-backup/ci/tasks/cfops_backup.yml
#     params:
#       TARGET_TILE: mysql-tile
#       OPS_MANAGER_HOSTNAME: {{ops-manager-hostname}}
#       # OPS_MANAGER_PRIVATE_IP_ADDRESS: {{ops-manager-private-ip}}
#       OPS_MANAGER_UI_USER: {{ops-manager-ui-user}}
#       OPS_MANAGER_UI_PASSWORD: {{ops-manager-ui-password}}
#       OPS_MANAGER_SSH_USER: {{ops-manager-ssh-user}}
#       OPS_MANAGER_SSH_PASSWORD: {{ops-manager-ssh-password}}
#   - put: s3-backup-mysql
#
# - name: backup-redis
#   serial: true
#   public: true
#   plan:
#   - get: pcf-backup-scripts
#     trigger: false
#   - get: trigger-daily-after-1am
#     trigger: true
#     passed:
#       - backup-mysql
#   - task: backup-redis
#     file: pcf-backup-scripts/pcf-cfops-backup/ci/tasks/cfops_backup.yml
#     params:
#       TARGET_TILE: redis-tile
#       OPS_MANAGER_HOSTNAME: {{ops-manager-hostname}}
#       # OPS_MANAGER_PRIVATE_IP_ADDRESS: {{ops-manager-private-ip}}
#       OPS_MANAGER_UI_USER: {{ops-manager-ui-user}}
#       OPS_MANAGER_UI_PASSWORD: {{ops-manager-ui-password}}
#       OPS_MANAGER_SSH_USER: {{ops-manager-ssh-user}}
#       OPS_MANAGER_SSH_PASSWORD: {{ops-manager-ssh-password}}
#   - put: s3-backup-redis
#
# - name: backup-rabbitmq
#   serial: true
#   public: true
#   plan:
#   - get: pcf-backup-scripts
#     trigger: false
#   - get: trigger-daily-after-1am
#     trigger: true
#     passed:
#       - backup-redis
#   - task: backup-rabbitmq
#     file: pcf-backup-scripts/pcf-cfops-backup/ci/tasks/cfops_backup.yml
#     params:
#       TARGET_TILE: rabbitmq
#       OPS_MANAGER_HOSTNAME: {{ops-manager-hostname}}
#       # OPS_MANAGER_PRIVATE_IP_ADDRESS: {{ops-manager-private-ip}}
#       OPS_MANAGER_UI_USER: {{ops-manager-ui-user}}
#       OPS_MANAGER_UI_PASSWORD: {{ops-manager-ui-password}}
#       OPS_MANAGER_SSH_USER: {{ops-manager-ssh-user}}
#       OPS_MANAGER_SSH_PASSWORD: {{ops-manager-ssh-password}}
#   - put: s3-backup-rabbitmq

# - name: clean-up-old-backup-files
#   serial: true
#   public: true
#   plan:
#   - get: trigger-daily-after-5am
#     trigger: true
#   - get: pcf-backup-scripts
#     trigger: false
#   - task: cleanup-backup
#     file: pcf-backup-scripts/pcf-cfops-backup/ci/tasks/cleanup-backup.yml
#     params:
#       FILE_REPO_IP: {{file-repo-ip}}
#       FILE_REPO_USER_ID: {{file-repo-user}}
#       FILE_REPO_PASSWORD: {{file-repo-password}}
#       FILE_REPO_PATH: {{file-repo-path}}
#       NUMBER_OF_DAYS_TO_KEEP_FILES: {{number-of-days-to-keep-backup-files}}
