groups:
- name: Backup
  jobs:
  - backup-opsman
  - backup-elastic-runtime
  - backup-mysql
  - backup-redis
  - backup-rabbitmq

resources:
- name: pcf-backup-scripts
  type: git
  source:
    branch: master
    uri: {{git-project-url}}
- name: s3-artifact
  type: s3
  source:
    bucket: {{s3-bucket}}
    regexp: {{s3-bucket-regex}}
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}
- name: trigger-daily-after-12am
  type: time
  source:
    start: 12:00 AM -0500
    stop: 2:00 AM -0500
- name: trigger-daily-after-12pm
  type: time
  source:
    start: 12:00 PM -0500
    stop: 2:00 PM -0500

jobs:
- name: backup-opsman
  serial: true
  plan:
  - get: pcf-backup-scripts
    trigger: false
  - get: trigger-daily-after-12am
    trigger: true
  - get: trigger-daily-after-12pm
    trigger: true
  - task: backup-opsman
    file: pcf-backup-scripts/pcf-cfops-backup/ci/tasks/cfops_backup.yml
    params:
      TARGET_TILE: ops-manager
      OPS_MANAGER_HOSTNAME: {{ops-manager-hostname}}
      # OPS_MANAGER_PRIVATE_IP_ADDRESS: {{ops-manager-private-ip}}
      OPS_MANAGER_UI_USER: {{ops-manager-ui-user}}
      OPS_MANAGER_UI_PASSWORD: {{ops-manager-ui-password}}
      OPS_MANAGER_SSH_USER: {{ops-manager-ssh-user}}
      OPS_MANAGER_SSH_PASSWORD: {{ops-manager-ssh-password}}
  - put: s3-artifact
    params:
      file: backupdir/*/ops-manager/*.zip
  - put: s3-artifact
    params:
      file: backupdir/*/ops-manager/*.tar.gz
  - put: s3-artifact
    params: 
      file: backupdir/*/ops-manager/*.json

