---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: silval/ubuntu-bosh-spruce-cf-fly
    tag: "latest"

inputs:
  - name: concourse-pipeline-samples

run:
  path: concourse-pipeline-samples/common/tasks/dummy-task.sh
