---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

inputs:
  - name: concourse-pipeline-samples

run:
  path: concourse-pipeline-samples/private-docker-registry/tasks/find-command.sh
