---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: localhost:5000/ubuntu
    insecure_registries: [ "localhost:5000" ]
    # username: myuser
    # password: mypass
    # email: x@x.com

inputs:
  - name: concourse-pipeline-samples

run:
  path: concourse-pipeline-samples/private-docker-registry/tasks/ls-command.sh
