---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: silval/ubuntu-bosh-spruce-cf-fly
    tag: "latest"

inputs:
  - name: pcf-backup-scripts

outputs:
  - name: backupdir

run:
  path: pcf-backup-scripts/pcf-cfops-backup/scripts/cfops_backup.sh
