---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/awscli-ubuntu
    tag: "latest"

run:
  path: pcf-backup-scripts/pcf-cfops-backup/scripts/post_backup_tasks.sh
