---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/awscli-ubuntu
    tag: "latest"

inputs:
  - name: cfops
  - name: s3cmd-release

run:
  path: pcf-backup-scripts/pcf-cfops-backup/scripts/pre_backup_tasks.sh
