---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs2
    tag: "latest"

inputs:
  - name: cfops-release
  - name: plugin-release

outputs:
  - name: cfops

run:
  path: sh
  args:
  - -exc
  - |
    # prepares cfops
    mv ./cfops-release/cfops_linux64 ./cfops/cfops
    chmod +x ./cfops/cfops
    # if [[ "$PLUGIN_DIR" != "NONE" ]]; then
    if [ "$PLUGIN_DIR" != "NONE" ]
    then
        # prepares plugin
        mkdir ./cfops/plugins
        tar xvf ./plugin-release/*.tgz
        mv $PLUGIN_DIR/* ./cfops/plugins
        chmod 755 ./cfops/plugins/*
    fi
    ls -alR ./cfops

params:
  PLUGIN_DIR:
