---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
  - name: pcf-backup-scripts
  - name: backupdir

run:
  path: pcf-backup-scripts/pcf-cfops-backup/scripts/scp-file-to-repo.sh
