---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: "git"
inputs:
  - name: environment-artifacts
run:
  path: sh
  args:
  - -exc
  - |
    echo "Do your integration test here"
    find .
