pcf_pks_api: ((pcf_pks_api))

opsman_domain_or_ip_address: ((opsman_domain_or_ip_address))
opsman_admin_username: ((opsman_admin_username))
opsman_admin_password: ((opsman_admin_password))
opsman_client_id: ((opsman_client_id))
opsman_client_secret: ((opsman_client_secret))

vcenter_host: ((vcenter_host))
vcenter_usr: ((vcenter_usr))
vcenter_pwd: ((vcenter_pwd))
vcenter_datacenter: ((vcenter_datacenter))
nsxv_manager_address: ((nsxv_manager_address))
nsxv_manager_admin_username: ((nsxv_manager_admin_username))
nsxv_manager_admin_password: ((nsxv_manager_admin_password))
nsxv_gen_mgr_transport_zone: ((nsxv_gen_mgr_transport_zone))
nsxv_gen_edge_cluster: ((nsxv_gen_edge_cluster))
vcenter_datastore: ((vcenter_datastore))
nsxv_gen_edge_name: ((nsxv_gen_edge_name))
nsxv_gen_vip_ip: ((nsxv_gen_vip_ip))
pks_api_cert_cn: ((pks_api_cert_cn))
