---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: silval/ubuntu-bosh-spruce-cf-fly
    tag: "latest"
inputs:
- name: concourse-pipeline-samples
- name: current-app-info

outputs:
- name: app-manifest-output

run:
  path: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/app-manifest-prep
