---
platform: linux

image: docker:///silval/ubuntu-bosh-spruce-cf-fly

inputs:
- name: concourse-pipeline-samples

- output: current-app-info

run:
  path: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/current-app-get-info
