---
platform: linux

image: docker:///djudorange/node-gulp-mocha

inputs:
- name: concourse-pipeline-samples
- name: current-app-info

run:
  path: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/load-tests
