---
platform: linux

image: docker:///djudorange/node-gulp-mocha

inputs:
- name: concourse-pipeline-samples

run:
  path: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/run-unit-tests
