---
platform: linux

image: docker:///silval/ubuntu-bosh-spruce-cf-fly

inputs:
  - name: concourse-pipeline-samples

run:
  path: concourse-pipeline-samples/docker-image-update/ci/tasks/dummy-task.sh
