---
resources:
- name: my-image
  type: s3
  source:
    access_key_id: ((s3-access-key-id))
    bucket: ((s3-bucket))
    endpoint: ((s3-endpoint))
    secret_access_key: ((s3-secret-access-key))
    regexp: ubuntu/ubuntu-(.*).tgz

jobs:
- name: hello-ubuntu-s3-with-resource
  plan:
  - get: my-image
    params:
      unpack: true
  - task: run-with-image-from-s3-using-resource-definition
    image: my-image
    config:
      platform: linux
      run:
        path: sh
        args:
        - -c
        - echo "I can run with image from resource definition"
