---
resources:
- name: my-resource
  type: git
  source:
    branch: master
    uri: https://github.com/pivotalservices/concourse-pipeline-samples.git

jobs:
- name: Automatically-Triggered-Job
  plan:
  - get: my-resource
    trigger: true
  - task: do-your-task-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Output of your job. It gets automatically triggered by any changes in the resource."


- name: Manually-Triggered-Job
  plan:
  - get: my-resource
    passed:
      - Automatically-Triggered-Job
    trigger: false
  - task: do-your-manual-task-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Output of your manually triggered task."
